# Generated by Django 5.2.5 on 2025-08-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_question_answer_remove_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
