# Generated by Django 5.2.5 on 2025-08-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_question_studentexamsession_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
